import React, { useState } from 'react';
import './App.css';


function App() {
  
	const [linkRepo, setLinkRepo] = useState("")


	const handleChangeLinkRepo = (event: React.ChangeEvent<HTMLInputElement>) => {
		setLinkRepo(event.target.value)
	}

	const sendLinkRepo = async () => {
		const summaryContent = document.getElementById("summaryContent") as HTMLTextAreaElement;
		summaryContent.value = "Generating summary ... Please wait";
		try {
			const response = await fetch('http://localhost:5001/getSummary', {
				method: 'POST',
				headers: {
					'Access-Control-Allow-Origin' : '*',
					'Access-Control-Allow-Methods':'GET,PUT,POST,DELETE,PATCH,OPTIONS',
				},
				body: JSON.stringify({ linkRepo: linkRepo })
			});
			if (!response.ok) {
				throw new Error('Network response was not ok');
			}
			const data = await response.json();
			// console.log(data);
            summaryContent.value = data.summary;
		} catch (error) {
			console.error('Error:', error);
		}
	}
	
	return (
		<div className="App">
			<div className='header'>
				<img src='https://i.imgur.com/SvIwWAN.png' className='logo'/>
				{/* Inserire switch dark/light mode */}
			</div>
			<div className='formLinkRepositoryContainer'>
				<input type='text' placeholder=' Repository Link' onChange={handleChangeLinkRepo} className='inputLinkRepository'/>
				<button onClick={sendLinkRepo} className='buttonGetSummary'>Get Summary</button>
			</div>
			<br></br>
			<div className='summaryContainer'>
				{/* Inserire titolo + summary */}
				<h2 className='titleSummary'>
					Summary Generated By CoReviewer
				</h2>
				<textarea className='summaryContent' id='summaryContent' readOnly rows={10}></textarea>
			</div>
		</div>
	);
}

export default App;
